---
- id: 1
  name: keppler
  url: "/keppler"
  method: GET
  active: true
  format_result: HTML
  position: 1
  deleted_at: 
  created_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-10-29 13:03:32.537103000 Z
    zone: &1 !ruby/object:ActiveSupport::TimeZone
      name: America/Caracas
    time: 2018-10-29 09:03:32.537103000 Z
  updated_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-10-29 13:03:32.537103000 Z
    zone: *1
    time: 2018-10-29 09:03:32.537103000 Z
- id: 2
  name: index
  url: "/"
  method: GET
  active: true
  format_result: HTML
  position: 2
  deleted_at: 
  created_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-10-29 13:05:17.039141000 Z
    zone: *1
    time: 2018-10-29 09:05:17.039141000 Z
  updated_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-10-29 13:05:17.039141000 Z
    zone: *1
    time: 2018-10-29 09:05:17.039141000 Z
